// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: customer.sql

package db

import (
	"context"
)

const getCustomerByID = `-- name: GetCustomerByID :one
select id, email, password, full_name, tel, address, confirmed from customer where id=$1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.Tel,
		&i.Address,
		&i.Confirmed,
	)
	return i, err
}
