// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
)

type Querier interface {
	ApproveRegister(ctx context.Context, arg ApproveRegisterParams) error
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateRegister(ctx context.Context, arg CreateRegisterParams) (PostRegister, error)
	GetCustomerByID(ctx context.Context, id int64) (Customer, error)
	GetPost(ctx context.Context) ([]Post, error)
	GetPostByID(ctx context.Context, id int64) (Post, error)
	GetPostByOwner(ctx context.Context, ownerID int64) ([]Post, error)
	GetTeacherByID(ctx context.Context, id int64) (Teacher, error)
	GetTeacherByPost(ctx context.Context, postID int64) ([]GetTeacherByPostRow, error)
}

var _ Querier = (*Queries)(nil)
